In [92]:
from numba import cuda

def is_gpu_available():
    try:
        return cuda.is_available()
    except:
        return False

gpu_available = is_gpu_available()
print(f"GPU is available: {gpu_available}")

GPU is available: True


In [93]:
if gpu_available:
    import cudf as pd
    from cuml.preprocessing import LabelEncoder, StandardScaler
    from cuml.model_selection import train_test_split
    from cuml.metrics import accuracy_score
else:
    import pandas as pd
    from sklearn.preprocessing import LabelEncoder, StandardScaler
    from sklearn.model_selection import train_test_split

from sklearn.metrics import classification_report, confusion_matrix

# Read Data
use cudf to read data into GPU

- delete unuseful colums(id, Name, City)
- Combine[(Academic Pressure, Work Pressure), (Working professional or student, Profession), (Study Satisfaction, Job Satisfaction)]
- Normalize or mapping

Gender       Age  Working Professional or Student  Academic Pressure  \
0       0  0.695360                               10           1.407041   
1       1 -1.161867                               55           0.693745   
2       1 -0.596624                               54           1.407041   
3       1 -1.484863                               55           1.407041   
4       0 -0.838871                                9          -1.446144   
5       0  1.502850                               26          -0.732848   
6       1  0.533862                               11           1.407041   
7       1 -0.192879                               55          -0.019551   
8       0 -1.323365                               54          -0.732848   
9       0  0.130117                               22           0.693745   

   Study Satisfaction  Sleep Duration  Dietary Habits  Degree  \
0           -0.689253               3               0      33   
1            0.022383               0               2      63   
2           -0.689253               1               0      21   
3           -1.400889               0               1      28   
4           -1.400889               1               2      28   
5            1.445655               1               0      82   
6           -0.689253               2               1      83   
7            0.734019               2               2      21   
8            1.445655               1               1      36   
9           -1.400889               1               0      84   

   Have you ever had suicidal thoughts ?  Work/Study Hours  Financial Stress  \
0                                      0         -1.363057         -0.699607   
1                                      1          0.193928          0.007793   
2                                      1         -0.844062         -1.407006   
3                                      1          0.972421         -1.407006   
4                                      1          0.712923          0.715193   
5                                      0          0.193928          1.422593   
6                                      0         -0.065570         -0.699607   
7                                      0          0.972421          0.007793   
8                                      0         -0.844062         -0.699607   
9                                      1          0.193928         -0.699607   

   Family History of Mental Illness  Depression  
0                                 0           0  
1                                 0           1  
2                                 0           1  
3                                 1           1  
4                                 1           0  
5                                 0           0  
6                                 0           0  
7                                 1           0  
8                                 1           0  
9                                 1           0

In [98]:
# delete any row with null value
df = df.dropna()

X = df.drop(columns=['Depression'])
y = df['Depression']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Logistic Regression

In [99]:
if gpu_available:
    from cuml.linear_model import LogisticRegression
else:
    from sklearn.linear_model import LogisticRegression


model = cuml.linear_model.LogisticRegression(max_iter=500)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(accuracy_score(y_test, y_pred))
print("confusion matrix:\n", confusion_matrix(y_test.to_numpy(), y_pred.to_numpy()))
print("classfication report:\n", classification_report(y_test.to_numpy(), y_pred.to_numpy()))

--------------------------------------------------Losgistic Regression--------------------------------------------------
Accuracy: 0.9298239373999644
Confusion Matrix:
 [[22143   864]
 [ 1109  3999]]
Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.96      0.96     23007
           1       0.82      0.78      0.80      5108

    accuracy                           0.93     28115
   macro avg       0.89      0.87      0.88     28115
weighted avg       0.93      0.93      0.93     28115

--------------------------------------------------Random Forest--------------------------------------------------
Accuracy: 0.9373643962297706
Confusion Matrix:
 [[22248   759]
 [ 1002  4106]]
Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.97      0.96     23007
           1       0.84      0.80      0.82      5108

    accuracy                           0.94     28115
   macro avg  

# Random Forest

In [104]:
if gpu_available:
    from cuml.ensemble  import RandomForestClassifier
else:
    from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=120, random_state=102)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(accuracy_score(y_test, y_pred))
print("confusion matrix:\n", confusion_matrix(y_test.to_numpy(), y_pred.to_numpy()))
print("classfication report:\n", classification_report(y_test.to_numpy(), y_pred.to_numpy()))

/usr/local/lib/python3.11/dist-packages/cuml/internals/api_decorators.py:368: UserWarning: For reproducible results in Random Forest Classifier or for almost reproducible results in Random Forest Regressor, n_streams=1 is recommended. If n_streams is > 1, results may vary due to stream/thread timing differences, even when random_state is set
  return init_func(self, *args, **kwargs)


0.9366084337234497
confusion matrix:
 [[22236   769]
 [ 1013  4093]]
classfication report:
               precision    recall  f1-score   support

           0       0.96      0.97      0.96     23005
           1       0.84      0.80      0.82      5106

    accuracy                           0.94     28111
   macro avg       0.90      0.88      0.89     28111
weighted avg       0.94      0.94      0.94     28111

